spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hospital_queue?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123123}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  open-in-view: false
  mvc:
    problemdetails:
      enabled: true
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

# JWT configuration
jwt:
  secret: ${JWT_SECRET:hospitalqueue-jwt-secret-key-should-be-very-long-and-secure-for-production}
  expiration: ${JWT_EXPIRATION:86400} # 24 hours in seconds

# Hardware communication settings
hardware:
  serial:
    port: ${SERIAL_PORT:COM3}
    baudrate: ${SERIAL_BAUDRATE:9600}
    enabled: ${SERIAL_ENABLED:true}

logging:
  level:
    root: info
    org:
      hibernate:
        SQL: warn
