version: '3.9'
services:
  mysql:
    image: mysql:8.4
    container_name: mysql-hospital-queue
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hospital_queue
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: hospital-queue-app
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
